---
# main tasks file for stem-minecraft
- include_vars: "../vars/{{ ansible_distribution }}.yml"

- include: "{{ ansible_distribution }}/install.yml"

- include: prereqs.yml

- include: provision-docker.yml

- debug: msg="You can now connect to your server at {{ hostvars[inventory_hostname].ansible_host }}"
