---
# provision tasks file for minecraft-container
- name: Create a container from the Minecraft image
  docker_container:
    name: "{{ container_name }}"
    image: "{{ minecraft_image_name }}"
    volumes:
      - "/{{ volume_name }}"
    exposed_ports:
      - "{{ minecraft_external_port }}"
    published_ports:
      - "{{ minecraft_internal_port }}:{{ minecraft_external_port }}"
    env:
      "{{ MINECRAFT_OPTIONS }}"
