---
# provision tasks file for minecraft-container
- name: Only use advanced Minecraft options if configured
  set_fact:
    MINECRAFT_OPTIONS: ""
  when: "{{ not include_minecraft_advanced_options }}"

- name: Create a container from the Minecraft image
  docker:
    name: "{{ container_name }}"
    image: "{{ minecraft_image_name }}"
    state: started
    expose:
      - "{{ minecraft_internal_port }}"
    volumes_from:
      - "{{ volume_name }}"
    ports:
      - "{{ minecraft_internal_port }}:{{ minecraft_external_port }}"
    env:
      "{{ MINECRAFT_OPTIONS }}"