---
# provision tasks file for minecraft-container
- name: Create Minecraft container volume
  file:
    path: "{{ ansible_env.HOME}}/{{ volume_name }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Create a container from the Minecraft image
  docker_container:
    name: "{{ container_name }}"
    image: "{{ minecraft_image_name }}"
    volumes:
      - "{{ ansible_env.HOME}}/{{ volume_name }}:/{{ volume_name }}"
    exposed_ports:
      - "{{ minecraft_external_port }}"
    published_ports:
      - "{{ minecraft_internal_port }}:{{ minecraft_external_port }}"
    env:
      "{{ MINECRAFT_OPTIONS }}"
