# Create an ssh-key

- name: Check for defined ssh_public_key_contents
  fail: msg="ssh_public_key_contents must be defined"
  when: '{{ ssh_public_key_contents is not defined }}'

- name: Create public key if it does not exist
  digital_ocean:
    state: present
    command: ssh
    name: "{{ ssh_remote_keyname }}"
    ssh_pub_key: "{{ ssh_public_key_contents }}"
    api_token: "{{ api_token }}"
  register: server_key

- set_fact:
    ssh_key_ids: "{{ server_key.ssh_key.id }}"