---
# provision tasks file for stem-minecraft

- include: get-image-id.yml
  when: "{{ image_id is not defined }}"

- include: create-ssh-key.yml
  when: "{{ not ssh_key_ids }}"

# Note that if droplet does exist ssh key id will not be added
- name: Create droplet if id does not exist
  digital_ocean:
    state: present
    command: droplet
    name: "{{ droplet_name }}"
    id: "{{ droplet_id }}"
    api_token: "{{ api_token }}"
    size_id: "{{ droplet_size }}"
    ssh_key_ids: "[{{ ssh_key_ids }}]"
    region_id: "{{ region }}"
    image_id: "{{ image_id }}"
    wait_timeout: 500

  register: server_droplet

- name: Add the instance to server group
  add_host:
      name: "{{ server_droplet.droplet.name }}"
      groups: server
      hostname: "{{ server_droplet.droplet.ip_address }}"
      ansible_host:  "{{ server_droplet.droplet.ip_address }}"
      ansible_user: root
      ansible_become: true
  no_log: True

# Wait for ssh
- name: Wait for ssh availability on host
  local_action: "wait_for port=22 host={{ hostvars[groups.server.0].ansible_host }} search_regex=OpenSSH delay=1"
  no_log: False

- name: Delay tasks for newly created instances
  pause:
    seconds: "{{ delay }}"
