# Create an ssh-key

- name: Check for defined ssh_public_key_contents
  fail: msg="ssh_public_key_contents must be defined"
  when: '{{ ssh_public_key_contents is not defined }}'

- name: Create public key if it does not exist
  ec2_key:
    state: present
    name: "{{ ssh_remote_keyname }}"
    key_material: "{{ ssh_public_key_contents }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
  register: server_key

- debug:
    var: server_key

- set_fact:
    ssh_remote_keyname: "{{ server_key.key.name }}"