- name: Create Docker Repo
  template:
    src: docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
    force: yes

- name: Update the cache
  command: yum -y update

- name: Install dependencies
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  retries: 3
  delay: 20
  with_items:
    - python-pip
    - docker-engine

- debug:
    var: image_ssh_user

- name: "Ensure {{ image_ssh_user }} is part of the docker group"
  user:
    name: "{{ image_ssh_user }}"
    group: docker

- debug: msg="after ensure docker user"